facturacionpy/facturacionpy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('home.urls','home'), namespace='home')),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

facturacionpy/home/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from home.views import Home

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='home/login.html'), name="logout"),
    
]

facturacionpy/inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaRemove, SubCategoriaView, \
SubCategoriaNew, SubCategoriaEdit



urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/remove/<int:pk>', CategoriaRemove.as_view(), name='categoria_remove'),
    
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
]

facturacionpy/home/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class Generico(models.Model):
    estado = models.BooleanField(default=True)
    fcreado = models.DateTimeField(auto_now_add=True)
    fmodificado = models.DateTimeField(auto_now=True)
    ucreado  = models.ForeignKey(User, on_delete=models.CASCADE)
    umodificado = models.IntegerField(blank=True, null=True)


    class Meta:
        abstract=True

facturacionpy/inv/models.py
from django.db import models

from home.models import Generico

# Create your models here.


class Categoria(Generico):
    descripcion = models.CharField(max_length=100, help_text='Descripción de la Categoría',unique=True)
    
    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = "Categorías"


class SubCategoria(Generico):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100, help_text='Descripción de la Categoría')

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()
    
    class Meta:
        verbose_name_plural = "Sub Categorías"
        unique_together = ('categoria', 'descripcion')

facturacionpy/inv/forms.py
from django import forms

from .models import Categoria, SubCategoria


class  CategoriaForm(forms.ModelForm):
    class Meta:
        model=Categoria
        fields=['descripcion', 'estado']
        labels={'descripcion':'Descripción de la Categoría', 'estado':'Estado'}
        widget={'descripcion':forms.TextInput}
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})


class  SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True).order_by('descripcion')
    )
    class Meta:
        model=SubCategoria
        fields=['categoria','descripcion', 'estado']
        labels={'descripcion':'Descripción de la SubCategoría', 'estado':'Estado'}
        widget={'descripcion':forms.TextInput}
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})
        self.fields['categoria'].empty_label =  "Seleccione Categoría"

facturacionpy/home/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

# Create your views here.

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'home/home.html'
    login_url = 'home:login'

facturacionpy/inv/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Categoria, SubCategoria
from .forms import CategoriaForm, SubCategoriaForm
from django.urls import reverse_lazy

# Create your views here.

class  CategoriaView(LoginRequiredMixin, generic.ListView):
    model=Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'home:login'


class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    context_object_name="obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url="home:login"

    def form_valid(self, form):
        form.instance.ucreado = self.request.user
        return super().form_valid(form)


class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    context_object_name="obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url="home:login"

    def form_valid(self, form):
        form.instance.umodificado = self.request.user.id
        return super().form_valid(form)


class CategoriaRemove(LoginRequiredMixin, generic.DeleteView):
    model = Categoria
    template_name="inv/categoria_del.html"
    context_object_name="obj"
    success_url=reverse_lazy("inv:categoria_list")


class  SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model=SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'home:login'


class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=SubCategoria
    template_name="inv/subcategoria_form.html"
    context_object_name="obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inv:subcategoria_list")
    login_url="home:login"

    def form_valid(self, form):
        form.instance.ucreado = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=SubCategoria
    template_name="inv/subcategoria_form.html"
    context_object_name="obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inv:subcategoria_list")
    login_url="home:login"

    def form_valid(self, form):
        form.instance.umodificado = self.request.user.id
        return super().form_valid(form)

facturacionpy/home/templates/home/home.html
{% extends 'base.html'%}

facturacionpy/home/templates/home/login.html
{% extends 'base.html'%}


{% block side_bar %}{% endblock side_bar %}
{% block top_bar %}{% endblock top_bar %}
{% block page_content %}{% endblock page_content %}
{% block footer %}{% endblock footer %}
{% block login %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                    <small class="text-danger">
                        {% if form.errors %}
                            {% for field in form %}
                                {% if field.errors %}    
                                    {% for error in field.errors %}    
                                        {{ error|escape }} 
                                    {% endfor %}                                
                                {% endif %} 
                            {% endfor %}

                            {% if form.non_field_errors %}    
                                    {% for error in form.non_field_errors %}    
                                        {{ error|escape }} 
                                    {% endfor %}                                
                                {% endif %} 
                        {% endif %}
                    </small>
                  </div>
                  <form class="user" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Usuario">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div> 
                                <button type="submit" class="btn btn-primary btn-user btn-block">Acceder</button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>


{% endblock login %}

facturacionpy/inv/templates/inv/categoria_del.html
{% extends 'base.html'%}


{% block page_content %}
<form class="form-inline"  method="POST">
{% csrf_token %}
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-danger shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliimar {{obj.descripcion}}?</div>
          <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Si, Eliminar</button>
          <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
        </div>  
        <div class="col-auto">
          <i class="far fa-question-circle fa-2x text-gray-300"></i>
        </div>    
      </div>
    </div>
  </div>
</div>
</form>
{% endblock page_content %}



{% block js_page %}

{% endblock js_page %}

facturacionpy/inv/templates/inv/categoria_form.html
{% extends 'base.html'%}


{% block page_content %}


<form  class="form-inline" method="POST">
  {% csrf_token %}
  <div class="col-xl-6 col-md-6 mb-6">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
    {% else %}
    <div class="card border-left-success shadow h-100 py-2">
    {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1"> 
              {% if obj %} Editar {% else %} Nueva {% endif %} Categoría
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
              <div class="col-10">
                <div class="input-group">
                  <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción" 
                  value="{% if obj %} {{obj.descripcion}}{% endif %}"> 
                </div>
              </div>
              <div class="col-2">
                <div class="form-group">
                  <label for="id_estado">Estado</label>
                  <input type="checkbox" name="estado" class="form-control"  id="id_estado" 
                  {% if obj.estado %} checked {% endif %} > 
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                <a href="{% url 'inv:categoria_list'%}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>

{% endblock page_content %}



{% block js_page %}



{% endblock js_page %}

facturacionpy/inv/templates/inv/categoria_list.html
{% extends 'base.html'%}


{% block page_content %}

<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Categoría</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(17px, 19px, 0px);">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {%if not obj %}
        <div class="alert alert-info">No hay Categorías</div>         
      {% else %}        
      <table class="table table-striped table-hover">
        <thead>          
            <th>Id</th>
            <th>Descripción</th>
            <th>Estado</th>
            <th>F. Creado</th>
            <th>F. Modificado</th>
            <th class="all">Acciones</th>
        </thead>
        <tbody>
          {% for item in obj %}
          <tr>
            <td>{{ item.id}}</td>
            <td>{{ item.descripcion}}</td>
            <td>{{ item.estado|yesno:"Activo,Inactivo"}}</td>
            <td>{{ item.fcreado|date:"d/m/Y H:i:s" }}</td>
            <td>{{ item.fmodificado|date:"d/m/Y H:i:s" }}</td>
            <td>
              <a href="{% url 'inv:categoria_edit'  item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
              <a href="{% url 'inv:categoria_remove' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
            </td>
          </tr>      
          {% endfor %}
        </tbody>
      
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}



{% block js_page %}

<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>

{% endblock js_page %}

facturacionpy/inv/templates/inv/subcategoria_form.html
{% extends 'base.html'%}


{% block page_content %}


<form  class="form-inline" method="POST">
  {% csrf_token %}
  <div class="col-xl-12 col-md-12 mb-12">
    {% if obj %}
    <div class="card border-left-warning shadow h-100 py-2">
    {% else %}
    <div class="card border-left-success shadow h-100 py-2">
    {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1"> 
              {% if obj %} Editar {% else %} Nueva {% endif %} Sub Categoría
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
              <div class="col-5">
                <div class="input-group">
                  {{form.categoria}}
                  <!-- <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción" 
                  value="{% if obj %} {{obj.descripcion}}{% endif %}">  -->
                </div>
              </div>
              <div class="col-2">
                <div class="input-group">
                  {{form.estado}}
                  <!-- <label for="id_estado">Estado</label>
                  <input type="checkbox" name="estado" class="form-control"  id="id_estado" 
                  {% if obj.estado %} checked {% endif %} >  -->
                </div>
              </div>
              <div class="col-5">
                <div class="input-group">
                  {{form.descripcion}}
                  <!-- <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción" 
                  value="{% if obj %} {{obj.descripcion}}{% endif %}">  -->
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                <a href="{% url 'inv:subcategoria_list'%}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>

{% endblock page_content %}



{% block js_page %}



{% endblock js_page %}

facturacionpy/inv/templates/inv/subcategoria_list.html
{% extends 'base.html'%}


{% block page_content %}

<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categoría</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(17px, 19px, 0px);">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {%if not obj %}
        <div class="alert alert-info">No hay Sub Categorías</div>         
      {% else %}        
      <table class="table table-striped table-hover">
        <thead>          
            <th>Categoria</th>
            <th>Id</th>
            <th>Descripción</th>
            <th>Estado</th>
            <th>F. Creado</th>
            <th>F. Modificado</th>
            <th class="all">Acciones</th>
        </thead>
        <tbody>
          {% for item in obj %}
          <tr>
            <td>{{ item.categoria.descripcion}}</td>
            <td>{{ item.id}}</td>
            <td>{{ item.descripcion}}</td>
            <td>{{ item.estado|yesno:"Activo,Inactivo"}}</td>
            <td>{{ item.fcreado|date:"d/m/Y H:i:s" }}</td>
            <td>{{ item.fmodificado|date:"d/m/Y H:i:s" }}</td>
            <td>
              <a href="{% url 'inv:subcategoria_edit'  item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
              <a href="{% url 'inv:categoria_remove' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
            </td>
          </tr>      
          {% endfor %}
        </tbody>
      
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}



{% block js_page %}

<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>

{% endblock js_page %}